<a href="https://colab.research.google.com/github/WGGaster/lesson1-introduction/blob/main/%D1%83%D1%80%D0%BE%D0%BA_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [91]:
import torch as t
import time

In [92]:
#1.1
t_3x4 =  t.rand(3,4)
t_2x3x4 =  t.zeros((2,3,4))
t_5x5 =  t.ones((5,5))
t_4x4 = t.range(0, 15).reshape(4, 4)
print('3x4', t_3x4)
print('2x3x4', t_2x3x4)
print('5x5', t_5x5)
print('4x4', t_4x4)


3x4 tensor([[0.5639, 0.7801, 0.6209, 0.8602],
        [0.1322, 0.3794, 0.2569, 0.5457],
        [0.6553, 0.6033, 0.7438, 0.6082]])
2x3x4 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
5x5 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
4x4 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])


/tmp/ipython-input-3134128752.py:5: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  t_4x4 = t.range(0, 15).reshape(4, 4)


In [93]:
#1.2
a =  t.rand(3, 4)
b =  t.rand(4, 3)
print(f'a = {a}')
print(f'b = {b}')


a_t = a.T
print(f'a_t = {a_t}')

matmul = t.matmul(a, b)
print(f'matmul = {matmul}')

element_mul = a * b.T
print(f'element_mul = {element_mul}')

sum = t.sum(a)
print(f'sum = {sum}')


a = tensor([[0.3266, 0.9482, 0.9751, 0.2034],
        [0.1256, 0.3541, 0.0840, 0.9848],
        [0.7022, 0.6276, 0.3703, 0.5820]])
b = tensor([[0.7155, 0.7004, 0.2010],
        [0.4133, 0.6792, 0.5945],
        [0.4795, 0.8609, 0.7223],
        [0.1190, 0.4650, 0.4607]])
a_t = tensor([[0.3266, 0.1256, 0.7022],
        [0.9482, 0.3541, 0.6276],
        [0.9751, 0.0840, 0.3703],
        [0.2034, 0.9848, 0.5820]])
matmul = tensor([[1.1174, 1.8069, 1.4274],
        [0.3937, 0.8587, 0.7501],
        [1.0087, 1.5075, 1.0498]])
element_mul = tensor([[0.2337, 0.3920, 0.4676, 0.0242],
        [0.0879, 0.2405, 0.0723, 0.4579],
        [0.1411, 0.3731, 0.2675, 0.2681]])
sum = 6.283802509307861


In [94]:
#1.3
t_5x5x5 = t.arange(125).reshape(5, 5, 5)
print(t_5x5x5)
print(t_5x5x5[0,0,:])
print(t_5x5x5[-1,:,-1])
print(t_5x5x5[2, 1:3, 1:3])
print(t_5x5x5[::2, ::2, ::2])

tensor([[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24]],

        [[ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49]],

        [[ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59],
         [ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74]],

        [[ 75,  76,  77,  78,  79],
         [ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124]]])
tensor([0, 1, 2, 3, 4])
tensor([104, 109, 114, 119, 124])
tensor([[56, 57],
        [61, 6

In [95]:
#1.4
t_6x4 = t.arange(24).reshape(6, 4)
print(t_6x4)
print(t_6x4.reshape(2, 12))
print(t_6x4.reshape(3, 8))
print(t_6x4.reshape(2, 3, 4))
print(t_6x4.reshape(2, 2, 2, 3))




tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[[ 0,  1,  2],
          [ 3,  4,  5]],

         [[ 6,  7,  8],
          [ 9, 10, 11]]],


        [[[12, 13, 14],
          [15, 16, 17]],

         [[18, 19, 20],
          [21, 22, 23]]]])


In [101]:
#2.1
x = t.tensor(6., requires_grad=True)
y = t.tensor(3., requires_grad=True)
z = t.tensor(9., requires_grad=True)

f = x ** 2 + y ** 2 + z ** 2 + 2 * x * y * z
print('f = ', f)
print()
f.backward()

print('градиент по x:', x.grad.item())
print('градиент по y:', y.grad.item())
print('градиент по z:', z.grad.item())

print()

x = x.item()
y = y.item()
z = z.item()

print('проверка аналитически:')
print(2 * x + 2 * y * z)
print(2 * y + 2 * x * z)
print(2 * z + 2 * y * x)
print('соответственно.')

f =  tensor(450., grad_fn=<AddBackward0>)

градиент по x: 66.0
градиент по y: 114.0
градиент по z: 54.0

проверка аналитически:
66.0
114.0
54.0
соответственно.


In [102]:
#2.2
def mse(y_pred, y_true):
  return t.mean((y_pred - y_true) ** 2)

t.manual_seed(42)
n = 5
x = t.randn(5)
y_true = 2 * x + 3.4 + t.randn(n)
w = t.tensor(2., requires_grad=True)
b = t.tensor(0., requires_grad=True)
y_pred = w * x + b
print('loss =', loss := mse(y_pred, y_true))
loss.backward()
print('w =', w.grad, 'и b =', b.grad)

loss = tensor(15.5540, grad_fn=<MeanBackward0>)
w = tensor(0.3106) и b = tensor(-7.6452)


In [104]:
#2.3
def sin(x):
  return t.sin(x ** 2 + 1)


x1 = t.tensor(2., requires_grad=True)
y1 = sin(x1)
y1.backward()
print('градиент =', x1.grad)

x2 = t.tensor(2., requires_grad=True)
y2 = sin(x2)
print('градиент, выявленный аналитически:', t.autograd.grad(y2, x2)[0].item())

градиент = tensor(1.1346)
градиент, выявленный аналитически: 1.1346487998962402


In [105]:
#3.1
t.manual_seed(42)

a = t.rand(64, 1024, 1024)
b = t.rand(128, 512, 512)
c = t.rand(256, 256, 256)


In [106]:
#3.2

def measure_time_cpu(func, *args, **kwargs):
    start_time = time.time()
    _ = func(*args, **kwargs)
    end_time = time.time()
    return end_time - start_time

def measure_time_gpu(func, *args, **kwargs):
    start_event = t.cuda.Event(enable_timing=True)
    end_event = t.cuda.Event(enable_timing=True)

    start_event.record()
    _ = func(*args, **kwargs)
    end_event.record()

    end_event.synchronize()
    elapsed = start_event.elapsed_time(end_event)
    return elapsed

In [110]:
#3.3
import pandas as pd

device = 'cuda' if t.cuda.is_available() else 'cpu'
a_gpu = a.to(device)
b_gpu = b.to(device)
c_gpu = c.to(device)

# Инициализация списка для хранения результатов
results = []

# Определение операций для сравнения (используем совместимые тензоры)
operations = [
    ("Матричное умножение", t.matmul, (a_gpu, a_gpu.transpose(-1, -2))),
    ("Поэлементное сложение", t.add, (a_gpu, a_gpu)),
    ("Поэлементное уумножение", t.mul, (a_gpu, a_gpu)),
    ("Транспонирование", t.transpose, (a_gpu, 0, 1)),
    ("Сумма всех элементов", t.sum, (a_gpu,))
]

# Измерение времени для каждой операции (только один запуск измерений)
for op_name, op_func, op_args in operations:
    cpu_ms = measure_time_cpu(op_func, *op_args)
    if device == 'cuda':
        gpu_ms = measure_time_gpu(op_func, *op_args)
        speedup = cpu_ms / gpu_ms if gpu_ms and gpu_ms > 0 else None
    else:
        gpu_ms = None
        speedup = None

    results.append({
        "Операция": op_name,
        "CPU мс": cpu_ms,
        "GPU мс": gpu_ms if gpu_ms is not None else "N/A",
        "Ускорение": f"{speedup:.2f}x" if speedup is not None else "N/A"
    })

# Показать результаты
results_df = pd.DataFrame(results)
print(results_df)

                  Операция    CPU мс GPU мс Ускорение
0      Матричное умножение  3.007266    N/A       N/A
1    Поэлементное сложение  0.147870    N/A       N/A
2  Поэлементное уумножение  0.136962    N/A       N/A
3         Транспонирование  0.000059    N/A       N/A
4     Сумма всех элементов  0.026428    N/A       N/A
