<a href="https://colab.research.google.com/github/WGGaster/lesson1-introduction/blob/main/%D1%83%D1%80%D0%BE%D0%BA_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import torch as t
import time

In [24]:
#1.1
t34 =  t.rand(3,4)
t234 =  t.zeros((2,3,4))
t55 =  t.ones((5,5))
t44 = t.range(0, 15).reshape(4, 4)
print(t34, t234, t55, t44, sep='\n')

tensor([[0.0497, 0.1270, 0.6131, 0.6823],
        [0.8895, 0.0390, 0.0185, 0.4882],
        [0.6852, 0.3290, 0.9891, 0.5218]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])


/tmp/ipython-input-1614930642.py:4: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  t44 = t.range(0, 15).reshape(4, 4)


In [18]:
#1.2
a =  t.rand(3, 4)
b =  t.rand(4, 3)
print(f'a = {a}')
print(f'b = {b}')


a_t = a.T
print(f'a_t = {a_t}')

matmul = t.matmul(a, b)
print(f'matmul = {matmul}')

element_mul = a * b.T
print(f'element_mul = {element_mul}')

sum = t.sum(a)
print(f'sum = {sum}')


a = tensor([[0.4778, 0.9919, 0.3619, 0.8215],
        [0.1928, 0.4531, 0.3895, 0.6432],
        [0.4972, 0.2749, 0.5334, 0.3706]])
b = tensor([[0.1746, 0.9064, 0.3494],
        [0.4288, 0.5713, 0.7283],
        [0.0368, 0.7516, 0.8435],
        [0.1961, 0.8233, 0.6377]])
a_t = tensor([[0.4778, 0.1928, 0.4972],
        [0.9919, 0.4531, 0.2749],
        [0.3619, 0.3895, 0.5334],
        [0.8215, 0.6432, 0.3706]])
matmul = tensor([[0.6832, 1.9481, 1.7184],
        [0.3685, 1.2559, 1.1360],
        [0.2970, 1.3136, 1.0601]])
element_mul = tensor([[0.0834, 0.4254, 0.0133, 0.1611],
        [0.1748, 0.2589, 0.2927, 0.5295],
        [0.1737, 0.2002, 0.4499, 0.2363]])
sum = 6.007833003997803


In [31]:
#1.3
t555 = t.arange(125).reshape(5, 5, 5)
print(t555)
print(t555[0,0,:])
print(t555[-1,:,-1])
print(t555[2, 1:3, 1:3])
print(t555[::2, ::2, ::2])

tensor([[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24]],

        [[ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49]],

        [[ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59],
         [ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74]],

        [[ 75,  76,  77,  78,  79],
         [ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124]]])
tensor([0, 1, 2, 3, 4])
tensor([104, 109, 114, 119, 124])
tensor([[56, 57],
        [61, 6

In [36]:
#1.4
t64 = t.arange(24).reshape(6, 4)
print(t64)
print(t64.reshape(2, 12))
print(t64.reshape(3, 8))
print(t64.reshape(2, 3, 4))
print(t64.reshape(2, 2, 2, 3))




tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[[ 0,  1,  2],
          [ 3,  4,  5]],

         [[ 6,  7,  8],
          [ 9, 10, 11]]],


        [[[12, 13, 14],
          [15, 16, 17]],

         [[18, 19, 20],
          [21, 22, 23]]]])


In [53]:
#2.1
x = t.tensor(6., requires_grad=True)
y = t.tensor(3., requires_grad=True)
z = t.tensor(9., requires_grad=True)

f = x ** 2 + y ** 2 + z ** 2 + 2 * x * y * z
print(f)
print()
f.backward()

print('градиенты:')
print(x.grad)
print(y.grad)
print(z.grad)

print()

x = x.item()
y = y.item()
z = z.item()

print('проверка аналитически:')
print(2 * x + 2 * y * z)
print(2 * y + 2 * x * z)
print(2 * z + 2 * y * x)

tensor(450., grad_fn=<AddBackward0>)

градиенты:
tensor(66.)
tensor(114.)
tensor(54.)

проверка аналитически:
66.0
114.0
54.0


In [57]:
#2.2
def mse(y_pred, y_true):
  return t.mean((y_pred - y_true) ** 2)

t.manual_seed(42)
n = 5
x = t.randn(5)
y_true = 2 * x + 3.4 + t.randn(n)
w = t.tensor(2., requires_grad=True)
b = t.tensor(0., requires_grad=True)
y_pred = w * x + b
print(loss := mse(y_pred, y_true))
loss.backward()
print(w.grad, b.grad)

tensor(15.5540, grad_fn=<MeanBackward0>)
tensor(0.3106) tensor(-7.6452)


In [82]:
#2.3
def sin(x):
  return t.sin(x ** 2 + 1)


x1 = t.tensor(2., requires_grad=True)
y1 = sin(x1)
y1.backward()
print(x1.grad)

x2 = t.tensor(2., requires_grad=True)
y2 = sin(x2)
print(t.autograd.grad(y2, x2)[0])

tensor(1.1346)
tensor(1.1346)


In [83]:
#3.1
t.manual_seed(42)

a = t.rand(64, 1024, 1024)
b = t.rand(128, 512, 512)
c = t.rand(256, 256, 256)


In [84]:
#3.2

def measure_time_cpu(func, *args, **kwargs):
    start_time = time.time()
    _ = func(*args, **kwargs)
    end_time = time.time()
    return end_time - start_time

def measure_time_gpu(func, *args, **kwargs):
    start_event = t.cuda.Event(enable_timing=True)
    end_event = t.cuda.Event(enable_timing=True)

    start_event.record()
    _ = func(*args, **kwargs)
    end_event.record()

    end_event.synchronize()
    elapsed = start_event.elapsed_time(end_event)
    return elapsed

In [89]:
#3.3
import pandas as pd

device = 'cuda' if t.cuda.is_available() else 'cpu'
a_gpu = a.to(device)
b_gpu = b.to(device)
c_gpu = c.to(device)

# Инициализация списка для хранения результатов
results = []

# Определение операций для сравнения (используем совместимые тензоры)
operations = [
    ("Матричное умножение", t.matmul, (a_gpu, a_gpu.transpose(-1, -2))),
    ("Поэлементное сложение", t.add, (a_gpu, a_gpu)),
    ("Поэлементное уумножение", t.mul, (a_gpu, a_gpu)),
    ("Транспонирование", t.transpose, (a_gpu, 0, 1)),
    ("Сумма всех элементов", t.sum, (a_gpu,))
]

# Измерение времени для каждой операции (только один запуск измерений)
for op_name, op_func, op_args in operations:
    cpu_ms = measure_time_cpu(op_func, *op_args)
    if device == 'cuda':
        gpu_ms = measure_time_gpu(op_func, *op_args)
        speedup = cpu_ms / gpu_ms if gpu_ms and gpu_ms > 0 else None
    else:
        gpu_ms = None
        speedup = None

    results.append({
        "Операция": op_name,
        "CPU мс": cpu_ms,
        "GPU мс": gpu_ms if gpu_ms is not None else "N/A",
        "Ускорение": f"{speedup:.2f}x" if speedup is not None else "N/A"
    })

# Показать результаты
results_df = pd.DataFrame(results)
print(results_df)

                  Операция    CPU мс GPU мс Ускорение
0      Матричное умножение  3.729920    N/A       N/A
1    Поэлементное сложение  0.144000    N/A       N/A
2  Поэлементное уумножение  0.135714    N/A       N/A
3         Транспонирование  0.000059    N/A       N/A
4     Сумма всех элементов  0.027966    N/A       N/A
